apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hsds
  name: hsds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsds
  template:
    metadata:
      labels:
        app: hsds
    spec:
      containers:
        - name: sn
          image: hdfgroup/hsds:0.7.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1G"
            limits:
              memory: "1G"
          volumeMounts:
            - name: accounts
              mountPath: "/config/passwd.txt"
              subPath: passwd.txt
            - name: config
              mountPath: "/config/config.yml"
              subPath: config.yml
            - name: override
              mountPath: "/config/override.yml"
              subPath: override.yml
          ports:
            - containerPort: 5101
          env:
            - name: NODE_TYPE
              value: sn
            - name: HEAD_PORT
              value: null # no head container
            - name: PASSWORD_FILE
              value: /config/passwd.txt
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-auth-keys
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-auth-keys
                  key: aws_secret_access_key
          livenessProbe:
            httpGet:
              path: /info
              port: 5101
            initialDelaySeconds: 5
            periodSeconds: 60
        - name: dn
          image: hdfgroup/hsds:0.7.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ["/sbin/killall5", "-15"]
          resources:
            requests:
              memory: "2G"
            limits:
              memory: "2G"
          volumeMounts:
            - name: config
              mountPath: "/config/config.yml"
              subPath: config.yml
            - name: override
              mountPath: "/config/override.yml"
              subPath: override.yml
          ports:
            - containerPort: 6101
          env:
            - name: NODE_TYPE
              value: dn
            - name: HEAD_PORT
              value: null # no head container
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-auth-keys
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-auth-keys
                  key: aws_secret_access_key
          livenessProbe:
            httpGet:
              path: /info
              port: 6101
            initialDelaySeconds: 5
            periodSeconds: 60
      volumes:
        - name: accounts
          secret:
            secretName: user-password
        - name: config
          configMap:
            name: hsds-config
