version: '2'
services:
  head:
    image: hdfgroup/hsds
    restart: ${RESTART_POLICY}
    mem_limit: ${HEAD_RAM}
    environment:
      - TARGET_SN_COUNT=${SN_CORES}
      - TARGET_DN_COUNT=${DN_CORES}
      - NODE_TYPE=head_node
      - ROOT_DIR=/data
      - BUCKET_NAME=${BUCKET_NAME}
    ports:
      - ${HEAD_PORT}
    volumes:
      - ${ROOT_DIR}:/data
      - ${PWD}/admin/config/:/config/

  dn:
    image: hdfgroup/hsds
    restart: ${RESTART_POLICY}
    mem_limit: ${DN_RAM}
    environment:
      - NODE_TYPE=dn
      - ROOT_DIR=/data
      - BUCKET_NAME=${BUCKET_NAME}
    ports:
      - ${DN_PORT}
    depends_on:
      - head
    volumes:
      - ${ROOT_DIR}:/data
      - ${PWD}/admin/config/:/config/
    links:
      - head
      - rangeget
  sn:
    image: hdfgroup/hsds
    restart: ${RESTART_POLICY}
    mem_limit: ${SN_RAM}
    environment:
      - SN_PORT=${SN_PORT}
      - NODE_TYPE=sn
      - ROOT_DIR=/data
      - BUCKET_NAME=${BUCKET_NAME}
      - HSDS_ENDPOINT=${HSDS_ENDPOINT}
    ports:
      - ${SN_PORT}:${SN_PORT}
    depends_on:
      - head
    volumes:
      - ${ROOT_DIR}:/data
      - ${PWD}/admin/config/:/config/
    links:
      - head

  rangeget:
    image: hdfgroup/hsds
    restart: ${RESTART_POLICY}
    mem_limit: ${RANGEGET_RAM}
    environment:
      - NODE_TYPE=rangeget
      - ROOT_DIR=/data
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - ${RANGEGET_PORT}
    depends_on:
      - head
    volumes:
      - ${ROOT_DIR}:/data
      - ${PWD}/admin/config/:/config/
    links:
      - head
